services:
  - type: web
    name: EliteBackend
    env: python
    plan: free
    rootDirectory: main_project  
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py collectstatic --noinput
      python manage.py migrate
      gunicorn main_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: DATABASE_URL
        fromDatabase:
          name: elite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: settings
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
    healthCheckPath: /admin/login/

  - type: postgresql
    name: elite
    plan: free
    ipAllowList: []
