services:
  # Backend (Django)
  - type: web
    name: EliteBackend
    env: python
    plan: free
    rootDirectory: main_project
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py collectstatic --noinput
      python manage.py migrate
      gunicorn main_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: DATABASE_URL
        fromDatabase:
          name: elite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: main_project.settings
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
    healthCheckPath: /admin/login/

  # Frontend (Vite + React)
  - type: web
    name: EliteFrontend
    env: node
    plan: free
    rootDirectory: Elite
    buildCommand: |
      npm install
      npm run build
    startCommand: |
      npm install -g serve
      serve -s dist
    envVars:
      - key: VITE_API_URL
        value: https://elitebackend.onrender.com
      - key: NODE_VERSION
        value: 18.x
    staticPublishPath: ./dist

databases:
  - name: elite
    plan: free
    databaseName: elite_db
    user: elite_user
    ipAllowList: []
