# Generated by Django 5.1.5 on 2025-04-25 19:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_company_picture_6_siteconfiguration_image_after_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='image_scrollable_3',
            new_name='image_scrolleable_3',
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='buttons_color',
            field=colorfield.fields.ColorField(choices=[('#007bff', 'Blue'), ('#28a745', 'Green'), ('#dc3545', 'Red'), ('#ffc107', 'Yellow'), ('#17a2b8', 'Cyan'), ('#6c757d', 'Gray'), ('#343a40', 'Dark'), ('#ffffff', 'White'), ('#000000', 'Black')], default='#FFFFFFFF', help_text='Click to choose color from palette', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='primary_color',
            field=colorfield.fields.ColorField(choices=[('#007bff', 'Blue'), ('#28a745', 'Green'), ('#dc3545', 'Red'), ('#ffc107', 'Yellow'), ('#17a2b8', 'Cyan'), ('#6c757d', 'Gray'), ('#343a40', 'Dark'), ('#ffffff', 'White'), ('#000000', 'Black')], default='#FFFFFFFF', help_text='Click to choose color from palette', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='secondary_color',
            field=colorfield.fields.ColorField(choices=[('#007bff', 'Blue'), ('#28a745', 'Green'), ('#dc3545', 'Red'), ('#ffc107', 'Yellow'), ('#17a2b8', 'Cyan'), ('#6c757d', 'Gray'), ('#343a40', 'Dark'), ('#ffffff', 'White'), ('#000000', 'Black')], default='#FFFFFFFF', help_text='Click to choose color from palette', image_field=None, max_length=25, samples=None),
        ),
    ]
