# Generated by Django 5.1.5 on 2025-04-27 20:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_siteconfiguration_buttons_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Website Reviews', 'verbose_name_plural': 'Website Reviews'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'List of orders', 'verbose_name_plural': 'List of orders'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'time_slot'], 'verbose_name': 'Calendar', 'verbose_name_plural': 'Calendar'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Images and colors', 'verbose_name_plural': 'Images and colors'},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='buttons_color',
            field=colorfield.fields.ColorField(blank=True, choices=[('', '---------'), ('#007BFFFF', 'Blue'), ('#1D097FFF', 'Blue2'), ('#28A745FF', 'Green'), ('#DC3545FF', 'Red'), ('#895188FF', 'Cyan'), ('#6C757DFF', 'Gray'), ('#CBC3FFFF', 'Gray2'), ('#651A89FF', 'Dark'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#CF1DBDFF', 'Violet'), ('#9027E9FF', 'Violet2')], default=None, help_text='Color for all action buttons', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='primary_color',
            field=colorfield.fields.ColorField(blank=True, choices=[('', '---------'), ('#007BFFFF', 'Blue'), ('#1D097FFF', 'Blue2'), ('#28A745FF', 'Green'), ('#DC3545FF', 'Red'), ('#895188FF', 'Cyan'), ('#6C757DFF', 'Gray'), ('#CBC3FFFF', 'Gray2'), ('#651A89FF', 'Dark'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#CF1DBDFF', 'Violet'), ('#9027E9FF', 'Violet2')], default=None, help_text='Main brand color used throughout the site', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='secondary_color',
            field=colorfield.fields.ColorField(blank=True, choices=[('', '---------'), ('#007BFFFF', 'Blue'), ('#1D097FFF', 'Blue2'), ('#28A745FF', 'Green'), ('#DC3545FF', 'Red'), ('#895188FF', 'Cyan'), ('#6C757DFF', 'Gray'), ('#CBC3FFFF', 'Gray2'), ('#651A89FF', 'Dark'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#CF1DBDFF', 'Violet'), ('#9027E9FF', 'Violet2')], default=None, help_text='Secondary color for accents and highlights', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('date', 'time_slot')},
        ),
    ]
