# Generated by Django 5.1.5 on 2025-04-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_client_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Images and colors', 'verbose_name_plural': 'Images and colors'},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Configuración actualmente activa'),
        ),
    ]
