# Generated by Django 5.1.5 on 2025-05-02 01:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_siteconfiguration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name': 'List of orders', 'verbose_name_plural': 'List of orders'},
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='buttons_color',
            field=colorfield.fields.ColorField(blank=True, choices=[('', '---------'), ('#007BFFFF', 'Blue'), ('#1D097FFF', 'Blue2'), ('#28A745FF', 'Green'), ('#DC3545FF', 'Red'), ('#895188FF', 'Cyan'), ('#6C757DFF', 'Gray'), ('#CBC3FFFF', 'Gray2'), ('#651A89FF', 'Dark'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#CF1DBDFF', 'Violet'), ('#9027E9FF', 'Violet2')], default=None, help_text='Color for all action buttons', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='primary_color',
            field=colorfield.fields.ColorField(blank=True, choices=[('', '---------'), ('#007BFFFF', 'Blue'), ('#1D097FFF', 'Blue2'), ('#28A745FF', 'Green'), ('#DC3545FF', 'Red'), ('#895188FF', 'Cyan'), ('#6C757DFF', 'Gray'), ('#CBC3FFFF', 'Gray2'), ('#651A89FF', 'Dark'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#CF1DBDFF', 'Violet'), ('#9027E9FF', 'Violet2')], default=None, help_text='Main brand color used throughout the site', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='secondary_color',
            field=colorfield.fields.ColorField(blank=True, choices=[('', '---------'), ('#007BFFFF', 'Blue'), ('#1D097FFF', 'Blue2'), ('#28A745FF', 'Green'), ('#DC3545FF', 'Red'), ('#895188FF', 'Cyan'), ('#6C757DFF', 'Gray'), ('#CBC3FFFF', 'Gray2'), ('#651A89FF', 'Dark'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#CF1DBDFF', 'Violet'), ('#9027E9FF', 'Violet2')], default=None, help_text='Secondary color for accents and highlights', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
